services:
  reverse-proxy:
    image: traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - easy-ticket-network

  migration:
    container_name: migration
    image: event-service
    depends_on:
      - easy-ticket-pg-db
    env_file:
      - ".dev.env"
    command: sh -c "go run ./cmd/migrate/main.go up"
    networks:
      - easy-ticket-network

  event-service:
    container_name: event-service
    build:
      context: ./event-service
      target: builder
    image: event-service
    env_file:
      - ".dev.env"
    expose:
      - "${EVENT_SERVICE_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.event.rule=Host(`easy.ticket.test`) && PathPrefix(`/api/event`)"
    environment:
      - ENV=dev
#    volumes:
#      - ./event-service:/go/src/app
    develop:
      watch:
        - action: sync+restart
          path: ./event-service/
          target: /go/src/app
          ignore:
            - .gitignore
    command: sh -c "go run ./"
    networks:
      - easy-ticket-network
    depends_on:
      - migration
      - easy-ticket-pg-db
  booking-service:
    container_name: booking-service
    build:
      context: ./booking-service
      target: builder
    image: booking-service
    env_file:
      - ".dev.env"
    expose:
      - "${BOOKING_SERVICE_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booking.rule=Host(`easy.ticket.test`) && PathPrefix(`/api/booking`)"
    environment:
      - ENV=dev
    #    volumes:
    #      - ./event-service:/go/src/app
    develop:
      watch:
        - action: sync+restart
          path: ./booking-service/
          target: /go/src/app
          ignore:
            - .gitignore
    command: sh -c "go run ./cmd/api/main.go"
    networks:
      - easy-ticket-network
    depends_on:
      - migration
      - easy-ticket-pg-db
      - redis-db
  easy-ticket-pg-db:
    container_name: easy-ticket-pg-db
    image: postgres:17.0
    env_file:
      - .dev.env
    volumes:
      - pg-easy-ticket-database:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - easy-ticket-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-db:
    container_name: redis-db
    image: redis:7.4.1
    env_file:
      - .dev.env
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - easy-ticket-network


networks:
  easy-ticket-network:
    driver: bridge


volumes:
  pg-easy-ticket-database:
    external: true




